### ISSUE TITLE
Quiz Lv 3 Feedback

### ISSUE THREAD

**Issue by udiiin** [mynameismaman/nxn-level3-quiz#1]
Halo Mas @mynameismaman, terima kasih untuk submissionnya..  
Saya ada beberapa feedback:

## 1

Penamaan variabel atau file:  
Usahakan menggunakan bahasa Inggris mas, biar terbiasa juga, hehee..  
Kalo misal kesulitan bisa manfaatkan google translate atau ChatGPT.  
Utk array: gunakan jamak (_plural_), untuk item tunggal gunakan _singular_.

Dan juga, berikana nama variabel secara deskriptif.  
Berikut yg perlu diperbaiki:

- `handleKlik` → `handleClick`
- `datas.map((rs) =>` → `data.map((item) =>`
- `dataArtikel.map((x,index) =>` → `articles.map((article, index) =>`
-  `data.map((y,index) =>` → `relatedArticles.map((article ,index) =>`
- `ambilapi.js` → `api.js`

## 2

Untuk mendapatkan semua slug, saya lihat mas menggunakan code ini:

```js
const countSlug = perPage * totalPages ;
const getAllSlug = await getMoreData(countSlug)
```

Ini bisa dipersimpel dengan langsung saja fetch dengan perPage=999
👉 https://hsi-sandbox.vercel.app/api/articles?perPage=999

## 3

Logonya sebaiknya langsung pakai file SVG saja, biar tidak kebanyakan code di component.

## 4

Filter popular/new:

<img width="432" alt="Screen Shot 2023-07-29 at 14 09 33" src="https://github.com/mynameismaman/nxn-level3-quiz/assets/129339659/885f9056-4684-4fc8-a154-fc5f0293e944">

- Font-nya belum sesuai  
  <img width="251" alt="Screen Shot 2023-07-29 at 14 08 39" src="https://github.com/mynameismaman/nxn-level3-quiz/assets/129339659/9955073c-a141-4593-8699-89473c7ca662">
- Typo: "news" → seharusnya "new"
- Pada saat awal membuka http://localhost:3000/ dibuat supaya opsi "new" sudah otomatis terpilih (warna pink)

## 5

File `.gitignore`:  
Pada saat awal membuat project Next.js, akan ada file `.gitignore`.  
Itu jangan dihapus..

<img width="671" alt="Screen Shot 2023-07-29 at 14 07 56" src="https://github.com/mynameismaman/nxn-level3-quiz/assets/129339659/03d1d853-4c7a-424b-98a4-e6402d6e9979">

## 6

Untuk related articles, di situ menggunakan ini utk load more:

```js
const [listNumber, setListNumber] = useState(PERPAGE);
...
<div onClick={() => setListNumber(listNumber+PERPAGE)} ...
```

Sebaiknya manfaatkan `useSWRInfinite` saja..

.

Semoga dimudahkan...  
Barokallaahu fiik..

**Comment by mynameismaman** [comment]
@udiiin  Afwan untuk point ke 6, apakah bisa menggunakan filter dalam mengambil data menggunakan  `useSWRInfinite`.  Bukankah dalam data API nya untuk kategorinya itu campur semua, sementara untuk related articles tugasnya menampilkan article dengan kategori yang sama. 

Afwan ana liat contoh untuk `useSWRInfinite` penggunaanya untuk meload data berdasarkan `page` . Misal kita klik tombol `Load More`,  `page=1` berubah menjadi `page=2`. Seperti itu yang ana pahami logikanya,

Afwan, kalo boleh tau logikanya sepertiapa untuk menggunakan `useSWRInfinite` ?

**Comment by udiiin** [comment]
Sipp Mas @mynameismaman 👍 

So far udah oke, bisa lanjut ke next level.

Saya sebenernya ada feedback lagi, tp ini bisa diimplemen di next quiz ya...

1.) Terdapat article yg sama pada halaman related articles

<img width="642" alt="Screen Shot 2023-08-05 at 15 46 17" src="https://github.com/mynameismaman/nxn-level3-quiz/assets/129339659/94a918f5-c0b4-4489-9db0-0d1403f6e63c">

2.) Terdapat article detail dengan related article 0, seharusnya tidak perlu ada bagian "You might also like..." ketika memang tidak ada related artikel.

<img width="479" alt="Screen Shot 2023-08-05 at 15 46 37" src="https://github.com/mynameismaman/nxn-level3-quiz/assets/129339659/d6951e58-d57f-4a26-b6af-3dc0b7e4fb2b">

.

Barokallaahu fiik... 🙏

**Comment by mynameismaman** [comment]
@udiiin siiap wafiik barakallah
